name: Publish
on:
  push:
    tags:
      - '*'

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Send start message to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_TO }}
          token: ${{ secrets.TG_TOKEN }}
          format: markdown
          message: |
            GitHub Actions Start
            Workflow Name: ${{ github.workflow }}
            Url: https://github.com/LemonNekoGH/easinteraction-for-cadence
            Trigger: `${{ github.event.ref_name }}` `${{ github.event.commits[0].id }}`
  publish:
    needs: start
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: LemonNekoGH/easinteraction-for-cadence
          token: ${{ secrets.PAT }}
      - run: echo "tag ${{ github.event.ref_name }}"
      - uses: LemonNekoGH/update-homebrew-formula-action@v0.1.0
        with:
          tag: ${{ github.event.ref_name }}
          description: Help users to generate code for easier contract interaction
          formula-name: EasiGen
          command-name: easi-gen
          url: https://github.com/LemonNekoGH/easinteraction-for-cadence
          homepage: https://github.com/LemonNekoGH/easinteraction-for-cadence
          license-name: MIT
          build-type: Go
          main: ./cmd/easi-gen/main.go
          ldflags: -X 'main.Version=#{version}'
      - name: Commit and push
        run: |
          git config user.email ${{ github.event.pusher.email }}
          git config user.name ${{ github.event.pusher.name }}
          git add Formula/easi-gen.rb
          git commit -m '[AUTO] Bump easi-gen version to ${{ github.event.ref }}'
          git push

      - name: Send end message to telegram
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TG_TO }}
          token: ${{ secrets.TG_TOKEN }}
          format: markdown
          message: |
            GitHub Actions End
            Workflow Name: ${{ github.workflow }}
            Url: https://github.com/LemonNekoGH/easinteraction-for-cadence
            Trigger: `${{ github.event.ref }}` `${{ github.event.commits[0].id }}`