name: Publish
on:
  push:
    tags:
      - '*'

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Send start message to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_TO }}
          token: ${{ secrets.TG_TOKEN }}
          format: markdown
          message: |
            GitHub Actions Start
            Workflow Name: ${{ github.workflow }}
            Url: https://github.com/LemonNekoGH/easinteraction-for-cadence
            Trigger: `${{ github.event.ref }}` `${{ github.event.commits[0].id }}`
  buildpublish:
    needs: start
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@v3
      # setup brew
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      # bump version if exists
      - name: bump version if exists
        run: brew install easi-gen && brew bump-formula-pr --url https://github.com/LemonNekoGH/easinteraction-for-cadence/archive/refs/tags/${{ github.event.ref }}.tar.gz
      - name: Send end message to telegram
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TG_TO }}
          token: ${{ secrets.TG_TOKEN }}
          format: markdown
          message: |
            GitHub Actions End
            Workflow Name: ${{ github.workflow }}
            Url: https://github.com/LemonNekoGH/easinteraction-for-cadence
            Trigger: `${{ github.event.ref }}` `${{ github.event.commits[0].id }}`